### ISSUE TITLE
New Logo Design

### ISSUE THREAD

**Issue by zularizal** [mo271/guessaday#3]
Hi @mo271 , I like your project, I am a graphic designer and I want to support your project by designing a new logo for your project and it is free.

What do you think?

**Comment by mo271** [comment]
Hi @zularizal! Thanks for you kind offer! I am actually quite happy with the logo. What kind of logo did you have in mind?

**Comment by zularizal** [comment]
Before design your logo, i have some questions for you.
What is your app name? How would you describe your app?

**Comment by mo271** [comment]
I don't think a new logo is necessary at this point.
